name: Python package

#on:
 # schedule:
  #  - cron: '0 0 * * *'      # Runs daily at midnight
  workflow_dispatch:          # Allows manual triggering of the workflow
  #push:
    #branches: [ "main" ]     # Uncomment to trigger on push to main branch
  #pull_request:
    #branches: [ "main" ]     # Uncomment to trigger on pull requests to main branch

jobs:
  build:
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10"]

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip setuptools wheel
        python -m pip install playwright
    
    - name: Install Playwright Browsers
      run: |
        python -m playwright install  # This downloads the browsers needed for Playwright to work

    - name: Install other dependencies
      run: |
        python -m pip install pytest pytest-playwright pytest-html pytest-xdist openpyxl
    
    
    # - name: Install Playwright Browsers
    #   run: |
    #     python -m playwright install
    # - name: Install pytest-palywright
    #   run: |
    #     python -m pip install pytest-playwright
    # - name: Install pytest-xdist
    #   run: |
    #     pip install pytest-xdist

    # - name: Install html reports
    #   run: |
    #     py -m pip install pytest-html

    # - name: Install reports
    #   run: |
    #     py -m pip install pytest-reporter-html1
    # - name: Install openpyxl
    #   run: |
    #     py -m pip install openpyxl

    - name: List installed packages
      run: |
        python -m pip list
    
    - name: Test with pytest
      run: |
        pytest tests/test_qademoPage2.py


